
* Vocabulary
** Section 1.1
- statement :: A sentence classified as something either true or false is a
               /statement/.
- sentential connectives :: /not/, /and/, /or/, /if\dots then/, /if and only if/.
  - conjunction :: \(p\land{}q\)
  - disjunction :: \(p\lor{}q\)
  - implication/conditional :: \(p\Rightarrow{}q\)
    - antecedant :: \(p\) statement
    - consequent :: \(q\) statement
  - biconditional :: \(p\Leftrightarrow{}q\)
  - negation :: \(\neg{}p\) represents the logical opposite of \(p\).
- tautology :: A statement which is true in all cases.
  - examples:
#+BEGIN_CENTER latex
\(\neg(p\land{}q)\Leftrightarrow[(\neg{}p)\lor(\neg{}q))]\) \\
\(\neg(p\lor{}q)\Leftrightarrow[(\neg{}p)\land(\neg{}q))]\) \\
\(\neg(p\Rightarrow{}q)\Leftrightarrow[p\lor(\neg{}q)]\) \\
#+END_CENTER

** Section 1.2
- universal quantifier :: \(\forall{}x,p(x)\)
- existential quantifier :: \(\exists{}x\ni{}p(x)\)

** Section 1.3
- deductive reasoning :: Applying a general principle to a particular case.
- \(p \Rightarrow q\) as a theorem :: When an implication is identified as a theorem, it is
     customary to refer to \(p\) as the *hypothesis* and \(q\) as the *conclusion*.
- converse :: \(p\Rightarrow{}q\) has the converse \(q \Rightarrow p\). Not tautologically equivalent to
              implication.
- inverse :: \(p \Rightarrow{} q\) has the inverse \((\neg p) \Rightarrow (\neg q)\). Not tautologically
             equivalent to implication.
- contrapositive :: Tautologically equivalent to the implication.
#+BEGIN_CENTER
$(p \Rightarrow{} q) \Leftrightarrow (\neg q \Rightarrow \neg p)$
#+END_CENTER

** Section 2.1
- subset :: $A\sube{}B$. $A$ is a *subset* of $B$ (or $A$ is *contained* in $B$). If we
            want to prove $A\sube{}B$, then we must prove "if $x\in{}A$, then $x\in{}B$".
  - proper subset :: $A\sub{}B$. $\forall{}a\in{}A, a\in{}B$, but $\exists{}b\in{}B\ni{}b\notin{}A$. That is, all elements
                     of $A$ are in $B$, but some elements of $B$ are not in $A$.
  - equal :: A set $A$ is equal to a set $B$ provided that $A\sube{}B$ and $A\supe{}B$ (or
             $A\sube{}B$ and $B\sube{}A$).
- closed interval :: $[a,b]$
- open interval :: $(a,b)$
- half--open (half--closed) interval :: $[a,b)$, or $(a,b]$.
- union :: $A \cup B = \{x \mid x\in A$ or $x\in B\}$
- intersection :: $A \cap B=\{x \mid x\in A$ and $x \in B\}$
  - If $A\cap{}B=\varnothing$, then $A$ and $B$ are said to be *disjoint*
- complement :: $A \setminus{} B=\{x\mid{}x\in{}A$ and $x\notin{}B\}$

** Section 2.2
- ordered pairs :: $(a,b)=\{\{a\},\{a,b\}\}$
- Cartesian product (cross product) :: $A\times{}B=\{(a,b)\mid{}a\in{}A$ and $b\in{}B\}$
- relation :: A *relation* between $A$ and $B$ is any subset $\R$ of $A\times{}B$. We say
              that an element a in $A$ is related by $\R$ to an element in $b$ in
              $B$ if $(a,b)\in{}\R$. The first set $A$ is referred to as the *domain*,
              of the relation and denoted dom $\R$. If $B=A$, then we speak of a
              relation $\R\sube{}A\times{}A$ being a *relation on* $A$.
  - equivalence relation :: A relation $\R$ is an *equivalence relation* if:
    1. $x\R{}x$ \hfill (reflexive property)
    2. If $x\R{}y$, then $y\R{}x$ \hfill (symmetric property)
    3. If $x\R{}y$ and $y\R{}z$, then $x\R{}z$ \hfill (transitive property)
  - equivalence class :: An equivalence class (with respect to $\R$) of $x\in{}S$ is
       defined to be the set
    #+BEGIN_CENTER latex
    $E_{x}=\{y\in{}S\mid{}y\R{}x\}$
    #+END_CENTER
    - partition :: Also, we see that an equivalence relation $\R$ on a set $S$
                   breaks $S$ into *disjoint* pieces in a natural way. A partition
                   of a set $S$ is a collection $\pow$ of nonempty subsets of
                   $S$ such that
      1. Each $x\in{}S$ belongs to some subset $A\in\pow$.
      2. For all $A,B\in\pow$, if $A\ne{}B$, then $A\cap{}B=\nil$.
    A member of $\pow$ is called a *piece* of the partition.

** Section 2.3
- identity function :: A function defined on a set A that maps each element in A
     onto itself is called the *identity function* on $A$, and is denoted
     $f^{-1}\circ{}f=i_{A}$. Furthermore, if $f(x)=y$, then $x=f^{-1}(y)$, so that
  #+BEGIN_CENTER latex
  $f\circ{}f^{-1}(y)=f(f^{-1}(y))=f(x)=y$.
  #+END_CENTER
  Thus, $f\circ{}f^{-1}=i_{B}$.

* Theorem
** Section 1.4
- This example shows a /direct proof/.
  - For every \(\epsilon>0\) there exists a \(\delta>0\) such that
  #+BEGIN_CENTER latex
  $1-\delta<x<1+\delta$ implies that $5-\epsilon<2x+3<5+\epsilon$.
  #+END_CENTER

  1. Begin by letting \epsilon be an arbitrary positive number, i.e. \(\epsilon>0\). We need to
     use this \(\epsilon\) to find a positive \(\delta\) with the property that
     #+BEGIN_CENTER latex
     \(1-\delta<x<1+\delta\) implies that \(5-\epsilon<2x+3<5+\epsilon\).
     #+END_CENTER
  2. Given any \(\epsilon>0\), let \(\delta=\epsilon/2\). \(\delta>0\), and whenever
     $$1-\delta<x<1+\delta$$
     #+BEGIN_EXPORT latex
     we have $$1-\frac{\epsilon}{2}<x<1+\frac{\epsilon}{2}$$
     so that $$2-\epsilon<2x<2+\epsilon$$
     and $$5-\epsilon<2x+3<5+\epsilon$$
     thus \\ 
     \center $1-\delta<x<1+\delta$ implies that $5-\epsilon<2x+3<5+\epsilon$.
     #+END_EXPORT
- This example shows a /indirect proof/.
  - Let \(f\) be an integrable function, so that
  #+BEGIN_CENTER latex
  If $\int_{0}^{1}f(x)dx\neq0$, then there exists a point $x$ in the interval $[0,1]$ such
  that $f(x)\neq0$.
  #+END_CENTER

  1. Symbolically, we have $p\Rightarrow{}q$, where
     #+BEGIN_CENTER latex
     $$p: \int_{0}^{1}f(x)dx\neq0,$$ \\
     $q: \exists{}x$ in $[0,1]\ni{}f(x)\neq0$.
     #+END_CENTER

     The contrapositive implication, $\neg{}q\Rightarrow{}\neg{}p$, can be written
     #+BEGIN_CENTER latex
     If for every $x$ in $[0,1]$, $f(x)=0$, then $\int_{0}^{1}f(x)dx=0$.
     #+END_CENTER
  2. This is obviously true. The integral of all 0 integrands is obviously 0.
- This example shows a /proof by contradiction/.
  - Let $x$ be a real number.
  #+BEGIN_CENTER latex
  If $x>0$, then $1/x>0$.
  #+END_CENTER

  1. Symbolically, we have $p\Rightarrow{}q$, where
     #+BEGIN_CENTER latex
     $p: x>0$ \\
     $q: 1/x>0$ \\
     #+END_CENTER

     so that, $(p\Rightarrow{}q)\Leftrightarrow{}((p\land{}\neg{}q)\Rightarrow{}c)$, where $c$ represents a contradiction.
  2. Begin by supposing $x>0$ and $1/x\le0$. Since $x>0$, we can multiply both
     sides of the inequality $1/x\le{}0$ by $x$ to obtain
     #+BEGIN_CENTER latex
     $$(x)\left(\frac{1}{x}\right)\le(x)(0)$$
     #+END_CENTER

     But $(x)(1/x)=1$ and $(x)(0)=0$, so we have $1\le0$, a contradiction to the
     (presumably known) fact that $1>0$. Having show that $p\land{}\neg{}q$ leads to a
     contradiction, we conclude that $p\Rightarrow{}q$.
- This example shows a /proof with absolute value/.
  - If $x$ is a real number, then $x\le\abs{x}$
  #+BEGIN_CENTER latex
  $s: x$ is a real number \\
  $r: x\le\abs{x}$ \\
  #+END_CENTER

  The definition of statement $r$ can be rewritten as:
  #+BEGIN_EXPORT latex
  \[\lvert{}x\rvert{}= 
    \begin{cases} 
      x & $if $x\ge{}0,  \\
      -x, & $if $x<0.
    \end{cases} \]
  #+END_EXPORT

  1. Since the definition is divided into two parts, it is natural to divide our
     proof into two cases. Thus statement $s$ is replaced by the equivalent
     disjunction $p\lor{}q$, where
     #+BEGIN_CENTER latex
     $p: x\ge0$ and $q: x<0$.
     #+END_CENTER

  2. The case to prove now is $(p\lor{}q)\Rightarrow{}r$, which is the same as $(p\Rightarrow{}r)\land(q\Rightarrow{}r)$.

  3. If $x\ge0$, then $x=\lvert{}x\rvert{}$. If $x<0$, then $-x>0$, so that
     $x<0<-x=\lvert{}x\rvert{}$. Or, $x\le\abs{x}$. Thus, $(p\Rightarrow{}r)\land(q\Rightarrow{}r)$. Hence, if
     $x$ is a real number, then $x\le\abs{x}$
** Section 2.3
- Let $f:A\longrightarrow{}B$. Then
  1. $f^{-1}:B\longrightarrow{}A$ is bijective.
  2. $f^{-1}\circ{}f=i_{A}$ and $f\circ{}f^{-1}=i_{B}$.
* Practice test
- question (1, d)
  - Define $A_{n}=(3,4+\frac{1}{n})$, an open interval in $\Real$, for each natural
    number $n$. Without writing a proof, determine $$\bigcap\limits_{n=1}^{\infty}A_{n}$$.
*answer*: When $n=1$, $A_{1}=(3,4+1)=(3,5)$. When $n=2$, the
$A_{1}=(3,4+\frac{1}{2})=(3,4.5)$. Here, consider $f(n)=4+\frac{2}{n}$, the
function for the upper bound of $A_{n}$ for each $n$. Here, the forward difference
quotient $\Delta{}f(1)=f(2)-f(1)=4.5-5<0$. Considering the function $f(n)$, this
difference quotient will always be negative. Therefore, the highest upper bound
over all the parts of the union will be $f(1)=5$. Since the lower bound function
is constant, the lowest lower bound over all the parts of the union will be 3.
Therefore, $A_{n}\sube{}(3,5)$, and $A_{n}=\{(3,4+\frac{1}{n})\mid{}n\in{}\Natural\}$.

- question (2, a) For all $x$, there exists $y$ such that for all $z$, if $y<x$
  then $z<y$.
  1. write the negation:
  2. Determine whether the original statement is true or false. Write "true" or
     "false", and then justify your answer by proving the original statment or
     the negation that you wrote in (a):
*answer 1*: There exists $x$ such that for all $y$, there exists $z$ such that
$y<x$ and $z\ge{}y$. \\
*answer 2*: Let $x$ be some constant $x_{0}$, such that $y<x_{0}$ for all y. Since this
$y$ can be any of all the numbers in $\Real$, say $y\ge{}x_{0}$, the statement $y<x_{0}$
is not true. Given a conjunction of a false statement and any other statement,
the conjunction is false. Since this statement is the negation of the original
statement and false, the original statement must be true. \\

- question (3,a)
  1. Suppose that $A=\{1,2,3\}$, $B=\{4,5\}$, and $C=\{6,7,8\}$. Let $R$ be the
     relation on $A\times{}C$ given by $\{(1,7),(3,6),(3,7)\}$ and $S$ by the relation
     on $B\times{}C$ given by $\{(4,7),(4,8),(5,6)\}$. Find $S^{-1}\circ{}R$.
  2. Given $R$ a relation on $A\times{}B$ and $S$ a relation on $B\times{}C$, prove that
     $(S\circ{}R)^{-1}=R^{-1}\circ{}S^{-1}$.
  3. Suppose that A and B are non-empty sets. Prove that $A\times{}B=B\times{}A$ if and only
     if $A=B$.
*answer 1*: Since $S$ is defined, and $S^{-1}=\{(c,b)\in{}C\times{}B\mid{}(b,c)\in{}S\}$,
$S^{-1}=\{(7,4),(8,4),(6,5)\}$. Then,
$S^{-1}\circ{}R=\{(7,4),(8,4),(6,5)\}\circ\{(1,7),(3,6),(3,7)\}$. This can be
simplified to $S^{-1}\circ{}R=\{(1,4),(3,5),(3,4)\}$. \\
*answer 2*: Consider $a\in{}A$, $b\in{}B$, and $c\in{}C$. $S\circ{}R$ is a relation such that
$(a,c)\in{}S\circ{}R\sube{}A\times{}C$. Thus, $(S\circ{}R)^{-1}=\{(c,a)\in{}C\times{}A\mid{}(a,c)\in{}S\circ{}R\}$.

Given $(a,b)\in{}R$, by definition of Inverse $R^{-1}=\{(b,a)\in{}B\times{}A\mid{}(a,b)\in{}R\}$.
Given $(b,c)\in{}S$, by definition of Inverse $S^{-1}=\{(c,b)\in{}C\times{}B\mid{}(b,c)\in{}S\}$.
Then,
$R^{-1}\circ{}S^{-1}=\{(c,a)\in{}C\times{}A\mid{}\exists{}b\in{}B\ni{}(a,b)\in{}R\land{}(b,c)\in{}S\}$.
However, this is the same as
$R^{-1}\circ{}S^{-1}=\{(c,a)\in{}C\times{}A\mid{}(a,c)\in{}S\circ{}R\}$, by the
definition of Cartesian Product.

Thus, since $(S\circ{}R)^{-1}$ and $R^{-1}\circ{}S^{-1}$ have the same definitions, it must be
that $(S\circ{}R)^{-1}=R^{-1}\circ{}S^{-1}$.

*answer 3*: (\Leftarrow) Let $A=B$. It must be that $A\times{}B=B\times{}A$, as having both leads to
$B\times{}B=B\times{}B$ or $A\times{}A=A\times{}A$ which are true. \\
(\Rightarrow) Let $A\times{}B=B\times{}A$, and remember $A$ and $B$ are non-empty sets. By definition,
$A\times{}B=\{(a,b)\mid{}a\in{}A\land{}b\in{}B\}$. Just as well, by definition,
$B\times{}A=\{(b,a)\mid{}a\in{}A\land{}b\in{}B\}$. Having this implies that for every $(a,b)\in{}A\times{}B$ and
the corresponding $(b,a)\in{}B\times{}A$, $(a,b)=(b,a)$. Thus, $A=B$. \\
In sum, this means $A\times{}B=B\times{}A$ if and only if $A=B$.

- question (4, a) Prove which one is true and which one is false.
  - For all subsets $S$ and $T$ of a universal set $U$, we have $U\setminus(S\setminus{}T)\sube(U\setminus{}S)\cup{}T$.
  - For all subsets $S$ and $T$ of a universal set $U$, we have $U\setminus(S\setminus{}T)\sube(U\setminus{}S)\cap{}T$.
*answer*: The first statement to consider, $U\setminus{}S$, has definition
$U\setminus{}S=\{u\in{}U\mid{}u\notin{}S\}$. Then $(U\setminus{}S)\cup{}T=\{u\in{}U\mid{}u\notin{}S\}\cup\{u\in{}T\}$. Which is to say
that $u\in{}U$, $u\notin{}S$, and $u\in{}T$, so that $(U\setminus{}S)\cup{}T=\{u\mid{}u\in{}U\land{}u\notin{}S\land{}u\in{}T\}$. \\
Consider the next statement $A$, in particular $U\setminus(S\setminus{}T)$. By definition
$S\setminus{}T=\{u\in{}S\mid{}u\notin{}T\}$. By definition, again, $U\setminus{}(S\setminus{}T)=\{u\in{}U\mid{}u\notin{}(S\setminus{}T)\}$,
that is $U\setminus{}(S\setminus{}T)=\{u\in{}U\mid{}u\notin{}S\land{}u\in{}T)\}$. Which is to say that $u\in{}U$, $u\notin{}S$, and
$u\in{}T$, so that $U\setminus{}(S\setminus{}T)=\{u\mid{}u\in{}U\land{}u\notin{}S\land{}u\in{}T\}$. \\
Thus, statement A, $U\setminus(S\setminus{}T)\sube(U\setminus{}S)\cup{}T$, is the true statement.
- question (4, b) Give a counterexample to the false statement, where $U=\Real$,
  and $S$ and $T$ are open interval in $\Real$.
*answer*: Let subset $S=\{x\in\Real\mid{}x>1\}$, and $T=\{x\in\Real\mid{}x<1\}$. $S$
and $T$ are disjoint, meaning $U\setminus{}(S\setminus{}T)=U\setminus{}S$. So, we have $U\setminus{}S\sube{}(U\setminus{}S)\cap{}T$. By
definition of set intersection, $(U\setminus{}S)\cap{}T=\{x\in\Real\mid{}x\in{}(U\setminus{}S)\land{}x\in{}T\}$, where
$U\setminus{}S=\{x\in\Real\mid{}x\in{}U\land{}x\notin{}S\}$. Here, we have $U\setminus{}S=\{x\in\Real\mid{}x\le{}1\}$, and
$(U\setminus{}S)\cap{}T=\{x\in\Real\mid{}x\le1\land{}x<1\}$ which is $(U\setminus{}S)\cap{}T=\{x\in\Real\mid{}x<1\}$. Just
as well, it can be seen that $U\setminus(S\setminus{}T)\supe(U\setminus{}S)\cap{}T$, which is sort of the opposite of
the statement B.
- question (5) Prove that, for all integers $p$ and $q$, if $pq$ is an even
  integer, then $p$ is an even integer or $q$ is an even integer.
*answer*: Consider the contrapositive of the predicate in the statement: For all
integers $p$ and $q$, if $p$ is an odd integer and $q$ is an odd integer, then
$pq$ is an odd integer. Let $p=2k-1$ and $q=2k-1$, for integers $k$. Then, it is
straightforward that $pq=(2k-1)(2k-1)=4k^{2}-4k+1=2(2k^{2}-2k)+1=2j+1$ for some
integer $j=2k^{2}-2k$ and is therefore odd. Thus, "for all integers $p$ and $q$, if
$p$ and $q$ are odd integers, then $pq$ is an odd integer" being true means that
its contrapositive is true, i.e. "for all integers $p$ and $q$, if $pq$ is an
even integer, then $p$ is an even integer or $q$ is an even integer" is true.
